/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DiagramaFlujo;

import java.awt.Color;
import javax.swing.JTextField;

/**
 *
 * @author Arles Cerrato
 */
public class Imprimir extends javax.swing.JPanel {

    //Atributos personalizados
    private boolean mover = true;
    int x;
    int y;
    boolean click;
    private final String nombre = "Imprimir";
    private boolean seleccion = false;
    private boolean seleccionImprimir = false;
    private int altura=40;
    private int anchura=360;
    
    //Constructor
    
    public Imprimir() {
        initComponents();
        this.setBackground(Color.blue);
    }
    
    //Mutadores
    
    public String getTexto(){
        return tf_texto_impresion.getText();
    }
    
    public String getNombre (){
        return nombre;
    }

    public boolean isSeleccion() {
        return seleccion;
    }

    public void setSeleccion(boolean seleccion) {
        this.seleccion = seleccion;
    }

    public boolean isSeleccionImprimir() {
        return seleccionImprimir;
    }

    public void setSeleccionImprimir(boolean seleccionImprimir) {
        this.seleccionImprimir = seleccionImprimir;
    }

    public JTextField getTf_texto_impresion() {
        return tf_texto_impresion;
    }

    public void setTf_texto_impresion(JTextField tf_texto_impresion) {
        this.tf_texto_impresion = tf_texto_impresion;
    }

    public boolean isMover() {
        return mover;
    }

    public void setMover(boolean mover) {
        this.mover = mover;
    }

    public int getAltura() {
        return altura;
    }

    public int getAnchura() {
        return anchura;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_imprimir = new javax.swing.JLabel();
        lb_abrirComilla = new javax.swing.JLabel();
        tf_texto_impresion = new javax.swing.JTextField();
        lb_cierreComillas = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        lb_imprimir.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        lb_imprimir.setForeground(new java.awt.Color(0, 0, 0));
        lb_imprimir.setText("IMPRIMIR  ");

        lb_abrirComilla.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        lb_abrirComilla.setForeground(new java.awt.Color(0, 0, 0));
        lb_abrirComilla.setText("\"");

        tf_texto_impresion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_texto_impresionMouseClicked(evt);
            }
        });

        lb_cierreComillas.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        lb_cierreComillas.setForeground(new java.awt.Color(0, 0, 0));
        lb_cierreComillas.setText("\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_imprimir)
                .addGap(18, 18, 18)
                .addComponent(lb_abrirComilla, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_texto_impresion, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_cierreComillas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_imprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_texto_impresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_cierreComillas)
                    .addComponent(lb_abrirComilla))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        click = true;
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        click = false;
    }//GEN-LAST:event_formMouseReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x2 = this.getX();
        int y2 = this.getY();
        if (click && mover) {
            x2 += evt.getX()-x;
            y2 += evt.getY()-y;
            this.setLocation(x2, y2);
        }      
    }//GEN-LAST:event_formMouseDragged

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        seleccion = true;
    }//GEN-LAST:event_formMouseClicked

    private void tf_texto_impresionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_texto_impresionMouseClicked
        // TODO add your handling code here:
        seleccionImprimir = true;
    }//GEN-LAST:event_tf_texto_impresionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_abrirComilla;
    private javax.swing.JLabel lb_cierreComillas;
    private javax.swing.JLabel lb_imprimir;
    private javax.swing.JTextField tf_texto_impresion;
    // End of variables declaration//GEN-END:variables
}
